function fnCrtChart(){paramAjx='opc_h=getDatGr';respAjax=excAjax('JntHomeChr',paramAjx,'sync');var respAjax=respAjax.replace("&Aacute;","Á");var respAjax=respAjax.replace("&Eacute;","É");var respAjax=respAjax.replace("&Iacute;","Í");var respAjax=respAjax.replace("&Oacute;","Ó");var respAjax=respAjax.replace("&Uacute;","Ú");if(respAjax.substring(0,1)!=='0'){return false;}
var dat=new Array();dat=respAjax.split('%$#!');n=respAjax.search("%$#!");respAjax=respAjax.substring(n+6);n=respAjax.search("%%EndGr%%");msgS=respAjax.substring(0,n-4);dat=msgS.split('%$#!');$("#h4titG4").html(dat[01]);$("#spTotG4").html(parseInt(dat[02])+parseInt(dat[03]));frmGr.tip_h.value=dat[00];frmGr.tit_h.value=dat[01];frmGr.v01_h.value=dat[02];frmGr.v02_h.value=dat[03];frmGr.t01_h.value=dat[04];frmGr.t02_h.value=dat[05];frmGr.v01_h.value=parseInt(frmGr.v01_h.value);frmGr.v02_h.value=parseInt(frmGr.v02_h.value);var config4={type:frmGr.tip_h.value,data:{labels:[frmGr.t01_h.value,frmGr.t02_h.value,],datasets:[{label:frmGr.tit_h.value,data:[frmGr.v01_h.value,frmGr.v02_h.value,],backgroundColor:['#000','#ccc'],}],},options:{responsive:true}};var ctx4=document.getElementById('chart-area4').getContext('2d');window.myPie=new Chart(ctx4,config4);respAjax=respAjax.substring(n+9);n=respAjax.search("%%EndGr%%");msgS=respAjax.substring(0,n-4);dat=msgS.split('%$#!');$("#h4titG5").html(dat[01]);$("#spTotG5").html(parseInt(dat[02])+parseInt(dat[03]));frmGr.tip_h.value=dat[00];frmGr.tit_h.value=dat[01];frmGr.v01_h.value=dat[02];frmGr.v02_h.value=dat[03];frmGr.t01_h.value=dat[04];frmGr.t02_h.value=dat[05];frmGr.v01_h.value=parseInt(frmGr.v01_h.value);frmGr.v02_h.value=parseInt(frmGr.v02_h.value);var config5={type:frmGr.tip_h.value,data:{labels:[frmGr.tit_h.value,],datasets:[{data:[frmGr.v01_h.value,],label:frmGr.t01_h.value,backgroundColor:['#470a68'],},{data:[frmGr.v02_h.value,],label:frmGr.t02_h.value,backgroundColor:['#ba0c2f'],}],},options:{responsive:true,scales:{yAxes:[{ticks:{min:0}}]}}};var ctx5=document.getElementById('chart-area5').getContext('2d');window.myPie=new Chart(ctx5,config5);respAjax=respAjax.substring(n+9);n=respAjax.search("%%EndGr%%");msgS=respAjax.substring(0,n-4);dat=msgS.split('%$#!');$("#h4titG6").html(dat[01]);$("#spTotG6").html((parseFloat(dat[02])+parseFloat(dat[03])+parseFloat(dat[04])+parseFloat(dat[05])+parseFloat(dat[06])+parseFloat(dat[07])).toFixed(2));frmGr.tip_h.value=dat[00];frmGr.tit_h.value=dat[01];frmGr.v01_h.value=dat[02];frmGr.v02_h.value=dat[03];frmGr.v03_h.value=dat[04];frmGr.v04_h.value=dat[05];frmGr.v05_h.value=dat[06];frmGr.v06_h.value=dat[07];frmGr.t01_h.value=dat[08];frmGr.t02_h.value=dat[09];frmGr.t03_h.value=dat[10];frmGr.t04_h.value=dat[11];frmGr.t05_h.value=dat[12];frmGr.t06_h.value=dat[13];var config6={type:frmGr.tip_h.value,data:{labels:[frmGr.t01_h.value,frmGr.t02_h.value,frmGr.t03_h.value,frmGr.t04_h.value,frmGr.t05_h.value,frmGr.t06_h.value,],datasets:[{data:[frmGr.v01_h.value,frmGr.v02_h.value,frmGr.v03_h.value,frmGr.v04_h.value,frmGr.v05_h.value,frmGr.v06_h.value,],label:frmGr.tit_h.value,backgroundColor:'#470a68',borderColor:'#470a68',fill:false,pointRadius:3,pointHoverRadius:5,}],},options:{responsive:true}};var ctx6=document.getElementById('chart-area6').getContext('2d');window.myPie=new Chart(ctx6,config6);respAjax=respAjax.substring(n+9);}
function fnLoadSections(){paramAjx='men_h=JntHomePro';$("#dvSPromNov").append(excAjax("JntHomePro",paramAjx,"sync"));paramAjx='men_h=JntHomeSur';$("#dvSPromNov").append(excAjax("JntHomeSur",paramAjx,"sync"));paramAjx='men_h=JntHomeNew';$("#dvSPromNov").append(excAjax("JntHomeNew",paramAjx,"sync"));}
function excDspProm(idProm,PgmName,HtmlName){$("#frmTemporal").remove();$('body').append('<form id="frmTemporal" name="frmTemporal" method="post"></form>');$("#frmTemporal").append("<input type='hidden' name='frmPromId' id='frmPromId"+"' value='"+idProm+"'>");if(PgmName==""||PgmName==null||PgmName==undefined){PgmName="JntDspProm";}
if(HtmlName==""||HtmlName==null||HtmlName==undefined){HtmlName="JntDspProm";}
excPgm(PgmName,HtmlName,'frmTemporal','');}
function excDspSurvey(idSurvey){$("#frmTemporal").remove();$('body').append('<form id="frmTemporal" name="frmTemporal" method="post"></form>');$("#frmTemporal").append("<input type='hidden' name='fil_h' id='fil_h"+"' value='"+idSurvey+"'>");excPgm('JntSurvDsp','JntSurvDsp','frmTemporal','');}
function fnCrtSegCntDn(){$('.cuenta-regresiva').countdown(frmCountDown.date.value+' '+frmCountDown.time.value,function(event){$('#dias').html(event.strftime('%D'));$('#horas').html(event.strftime('%H'));$('#minutos').html(event.strftime('%M'));$('#segundos').html(event.strftime('%S'));});}
function fnOpenDoc(doc){paramAjx='opc_h=dspNov&nDoc_h='+doc;respAjax=excAjax('JntOpenD',paramAjx,'sync');if(respAjax.substr(0,5)=='Error'){alert(respAjax);return false;}
window.open(respAjax,"_blank");paramAjx='opc_h=rmvNov&nDoc_h='+respAjax;setTimeout(function(){respAjax=excAjax('JntOpenD',paramAjx,'sync');},1000);}
function fnDisplayAviI(path,tit,wid,hei,boton,group,idDoc,prog,html){fnDspWinPdf(path,tit,wid,hei);setTimeout(function(){$('#msgWindow .modal-dialog .modal-content .modal-header .close').remove();actualHei=parseInt($('#msgWindow .modal-dialog .modal-content').css('height'));actualHei+=120;$('#msgWindow .modal-dialog .modal-content').css('height',actualHei+'px');rowToAdd='<div class="modal-body light" style="padding-top:0">'+'<div class="col-sm-6">'+'</div>'+'<div class="col-sm-6">'+'<a href="javascript:void(0);" '+'onclick="fnResAviI(\'SI\',\''+group+'\',\''+idDoc+'\',\''+prog+'\',\''+html+'\');" '+'class="btn full btn-blue-light" data-dismiss="modal">'+'Aceptar'+'</a>'+'</div>'+'</div>';$('#msgWindow .modal-dialog .modal-content').append(rowToAdd);},500);}
function fnResAviI(resp,group,idDoc,prog,html){paramAjx='opc_h=RespAviI&grp_h='+group+'&msg_h='+idDoc+'&rsp_h='+resp;respAjax=excAjax('JntHome',paramAjx,'sync');if(prog!==""&&prog!==null&&prog!==undefined&&html!==""&&html!==null&&html!==undefined){excPgm(prog,html,'','');return false;}
excPgm('JNTHOME','JNTHOME','','');}